import type { Preset } from './types.js';

export const PRESETS: Preset[] = [
  {
    id: 'quick',
    label: 'App Rápido',
    hint: 'Sem auth, sem banco — pronto para codar',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'crud',
    label: 'CRUD Simples',
    hint: 'Auth + banco, o básico de um serviço',
    defaults: {
      backend: 'nestjs',
      auth: 'jwt',
      database: 'postgres',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'full-oidc',
    label: 'App Completo OIDC',
    hint: 'OIDC + banco + cache, tudo configurado e seguro',
    defaults: {
      backend: 'nestjs',
      auth: 'oidc',
      database: 'postgres',
      cache: 'redis',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'realtime',
    label: 'Dados em Tempo Real',
    hint: 'WebSocket para updates ao vivo no frontend',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: ['websocket'],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'api-only',
    label: 'API Pura',
    hint: 'Backend sem frontend gerado',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'none',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'frontend-only',
    label: 'Frontend Puro',
    hint: 'SPA React sem backend gerado',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'custom',
    label: 'Customizado',
    hint: 'Definir tudo manualmente',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
];
