import type { Preset } from './types.js';

export const PRESETS: Preset[] = [
  {
    id: 'quick',
    label: 'Quick App',
    hint: 'No auth, no database — start coding immediately',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'crud',
    label: 'Simple CRUD',
    hint: 'Auth + database — the baseline for most services',
    defaults: {
      backend: 'nestjs',
      auth: 'jwt',
      database: 'postgres',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'full-oidc',
    label: 'Full OIDC App',
    hint: 'OIDC + database + cache — production-ready from day one',
    defaults: {
      backend: 'nestjs',
      auth: 'oidc',
      database: 'postgres',
      cache: 'redis',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'realtime',
    label: 'Real-Time Data',
    hint: 'WebSocket for live updates to the frontend',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: ['websocket'],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'api-only',
    label: 'API Only',
    hint: 'Backend without a generated frontend',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'none',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'frontend-only',
    label: 'Frontend Only',
    hint: 'React SPA without a generated backend',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
  {
    id: 'custom',
    label: 'Custom',
    hint: 'Choose everything manually',
    defaults: {
      backend: 'nestjs',
      auth: 'none',
      database: 'none',
      cache: 'none',
      queue: 'none',
      ai: 'none',
      realtime: [],
      frontend: 'react',
      packageManager: 'pnpm',
    },
  },
];
